version: 2.1
parameters:
  is_pr:
    type: boolean
    default: false
jobs:
  test_nodes:
    docker:
      - image: hoanito/mbr-ubuntu:1.1
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: mkdir -p /massbitroute/nodetest && cd /massbitroute/nodetest
      - checkout
      - run: apt install ssh git -y
      - run: export BUILD_BRANCH=$CIRCLE_BRANCH
      - run: 
          name: Get SSH KEY
          command: |
              sudo git clone http://ssh:1fdaf5d506fda56b4a50a5e3f24d68799e33cdd2@git.massbitroute.dev/massbitroute/ssh.git -b main /opt/ssh-key
              sudo cp /opt/ssh-key/ci-ssh-key  /root/.ssh/id_rsa
              sudo cp /opt/ssh-key/ci-ssh-key.pub  /root/.ssh/id_rsa.pub
              cat /root/.ssh/id_rsa
              cat /root/.ssh/id_rsa.pub
      - run: 
          name: Obtain GCE key
          command: echo $PROJECT_KEY > project_key.json
      - run: 
          name: Spawn core node
          command: cd scripts/single-node-test && sudo bash ./deploy-mb-core.sh $CIRCLE_BRANCH dev
      - run: 
          name: Update host files for nodes 
          command: cd scripts/single-node-test &&  sudo bash -x ./build-hosts-file.sh


# Orchestrate our job run sequence
workflows:
  version: 2

  massbitroute-ci-pr:
    when: << pipeline.parameters.is_pr >>
    jobs:
      - test_nodes

  massbitroute-ci-merged:
    jobs:
      - test_nodes:
          filters:
            branches:
              only: master

