version: 2.1

jobs:
  test_nodes:
    docker:
      - image: hoanito/mbr-ubuntu:1.1
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: mkdir -p /massbitroute/nodetest && cd /massbitroute/nodetest
      - checkout
      - run: 
          name: Obtain GCE key
          command: echo $PROJECT_KEY > project_key.json
      - run: 
          name: Run node/gateway test
          command: sudo bash single-node-test.sh 
          
# Orchestrate our job run sequence
workflows:
  massbitroute-ci:
    jobs:
      - test_nodes
